isNil, isTrue and isFalse constraints
muonsoft/validation pull request #28
Opened 2021-03-18 19:04 UTC by nqlad

2021-03-18 19:13 UTC, strider2038 requested changes

2021-03-18 19:13 UTC, strider2038 commented on it/basic.go
> +func IsNil() NilConstraint {
Не хватает комментариев с примерами

2021-03-18 19:13 UTC, strider2038 commented on it/basic.go
> +// NilConstraint checks that a value in strictly equal to `nil`. To check that values in blank use
Тут лучше не использовать кавычки. Они для маркдауна только выделяют текст.

2021-03-18 19:13 UTC, strider2038 commented on it/basic.go
> +type FalseConstraint struct {
Стоит ли разделять True и False constraint'ы? Я бы их объединил в BoolConstraint. В них все равно точная проверка по значению.

2021-03-20 17:17 UTC, strider2038 requested changes

2021-03-20 17:17 UTC, strider2038 commented on it/basic.go
> +	checkFalse           bool
К чему такие сложности? Можно просто использовать ожидаемое значение и сравнивать с ним

2021-03-20 17:17 UTC, strider2038 commented on it/basic.go
> +	falseMessageTemplate string
Достаточно одного шаблона. Все можно сделать проще.

```golang
type BoolConstraint struct {
	isIgnored bool
	value bool
	messageTemplate string
	code string
}

func IsTrue() BoolConstraint {
	return BoolConstraint{
		value: true,
		code: code.True,
		messageTemplate: message.True,
	}
}

func (c BoolConstraint) ValidateBool(value *bool, scope validation.Scope) error {
	if c.isIgnored || value == nil || c.value == *value {
		return nil
	}

	return c.newViolation(scope)
}
```

2021-03-20 17:17 UTC, strider2038 commented on it/basic.go
> +func (c NilConstraint) When(condition bool) NilConstraint {
Давай придерживаться единого подхода к комментариям. Описывать все методы, кроме методов `Validate...`. Так же порядок следования методов по важности: сначала `Name()`, затем `SetUp()`, затем методы настроек, потом методы валидации, затем приватные методы.

2021-03-21 15:46 UTC, strider2038 requested changes

2021-03-21 15:46 UTC, strider2038 commented on it/basic.go
> +func (c NilConstraint) When(condition bool) NilConstraint {
Не исправлено

2021-03-21 15:46 UTC, strider2038 commented on it/basic.go
> +	if c.isIgnored {
Поведение такое же как у `NotNil`.

2021-03-21 15:46 UTC, strider2038 commented on it/basic.go
> +	if c.isIgnored {
Поведение такое же как у `NotNil`.

2021-03-21 15:50 UTC, strider2038 commented on it/basic.go
> +	if (c.value && *value) || (!c.value && !*value) {
Зачем такое сложное условие? Почему просто не сравнивать с ожидаемым?

2021-03-21 15:51 UTC, strider2038 commented on it/basic.go
> +	if (c.value && *value) || (!c.value && !*value) {
У меня же был пример. Разве он не работает?

```golang
func (c BoolConstraint) ValidateBool(value *bool, scope validation.Scope) error {
	if c.isIgnored || value == nil || c.value == *value {
		return nil
	}

	return c.newViolation(scope)
}
```

2021-03-23 18:54 UTC, nqlad commented on it/basic.go
> +func (c NilConstraint) When(condition bool) NilConstraint {
а методы настроек в определенной сортировке?

2021-03-23 19:12 UTC, strider2038 commented on it/basic.go
> +func (c NilConstraint) When(condition bool) NilConstraint {
Вообще когда я работаю в Goland, то после написания структуры констрейнта делаю экшен `implement interface` и выбираю `Constraint`. Тогда IDE автоматически подставляет сначала SetUp, затем Name (сохраняется порядок как они перечислены в интерфейсе). Затем начинаю имплементировать типизированные виды констрейнтов. Между Name и методами валидации вставляю управляющие методы `When`, `Message`, т.к. они важнее самих методов валидации. В конце лучше оставлять методы валидации, т.к. это детали реализации, по идее они представляют наименьший интерес для пользователя (сначала важнее увидеть настройки ограничений, а затем реализацию). Как-то так :-)

2021-03-23 19:12 UTC, strider2038 approved these changes

2021-03-23 19:13 UTC, merged