Sequentially constraint
muonsoft/validation pull request #37
Opened 2021-05-03 18:19 UTC by nqlad

2021-05-03 18:20 UTC, nqlad commented
продолжил ветку с conditional constraint

2021-05-03 18:21 UTC, nqlad commented on contraint.go
> +type SequentiallyConstraint struct {
стоит ли данный класс оставить здесь, может правильней его расположить в iterable рядом с CountConstraint?

2021-05-03 19:15 UTC, strider2038 requested changes

2021-05-03 19:15 UTC, strider2038 commented on functions.go
> +			err := constraint.validateSequentiallyConstraints(scope, &violations, validate)
Сигнатура метода идентична с `ConditionalConstraint`. Мы говорили об этом. Нужно сделать общую абстракцию, чтобы не увеличивать число проверок.

2021-05-03 19:15 UTC, strider2038 commented on contraint.go
> +type SequentiallyConstraint struct {
1) Ты не можешь вынести этот констрейнт в отдельный пакет, т.к. тебе придется опубликовать приватный метод, который скрывает детали реализации (т.е. будет протекшая абстракция, которая не нужна клиенту библиотеки).
2) Это управляющий констрейнт, т.е. он управляет потоком выполнения. В пакете `it` - исполняющие констрейнты. Они не управляют потоком.

2021-05-03 19:15 UTC, strider2038 commented on contraint.go
>  type notFoundConstraint struct {
Приватные структуры лучше перемещать вниз. В первую очередь клиенту библиотеки должно быть интересно то, что экспортируется и что он может использовать.

2021-05-03 19:15 UTC, strider2038 commented on contraint.go
> +			isViolation = true
Зачем эта логика? При любой ошибке поток выполнения прерывается.

2021-05-03 19:15 UTC, strider2038 commented on examples_sequentially_validation_test.go
> +		validation.StringProperty(
Зачем тут `StringProperty`? Почему не обойтись более простым методом для примера? Можно вообще просто использовать `ValidateString`.

2021-05-03 19:15 UTC, strider2038 commented on contraint.go
> +type SequentiallyConstraint struct {
Не забудь про документацию

2021-05-04 14:16 UTC, strider2038 requested changes

2021-05-04 14:16 UTC, strider2038 commented on contraint.go
> +// Sequentially creates a SequentiallyConstraint that set of rules that should be validated step-by-step.
Неграмотно построенная фраза. Что устанавливает SequentiallyConstraint?

2021-05-04 14:16 UTC, strider2038 commented on contraint.go
> +// Example
Этот пример будет не нужен, если к этому методу прикрепить существующий runnable example.

2021-05-04 14:16 UTC, strider2038 commented on examples_sequentially_validation_test.go
> +	title := "aaa"
В качестве типовых значений в примерах часто используются foo и bar. Если у значения aaa нет особого смысла, то лучше использовать типовые значения.

2021-05-04 14:16 UTC, strider2038 commented on examples_sequentially_validation_test.go
> +func ExampleValidator_Validate_validationInterruptedAtFirstViolation() {
Лучше прикрепить к функции Sequentially

2021-05-04 14:16 UTC, strider2038 commented on functions.go
> +type ConstraintsPool interface {
Почему "пул"? Если подразумевается, что этот констрейнт может содержать другие, то каким образом это ограничение будет контролироваться? Зачем интерфейс экспортируется? Тем более с неэкспортируемым методом. То есть ты как бы заявляешь, что его можно использовать на клиентской стороне, но на самом деле - нельзя.

Как вариант, предлагаю имя `controlConstraint`.

2021-05-04 14:16 UTC, strider2038 commented on test/validate_sequentially_test.go
> +func TestValidate_InvalidValueAtFirstConstraintOfSequentiallyConstraint_ExpectViolations(t *testing.T) {
Имя метода

2021-05-04 14:29 UTC, strider2038 requested changes

2021-05-04 14:29 UTC, strider2038 commented on contraint.go
> +	for _, constraint := range c.constraints {
По-моему можно написать компактнее

```golang
for _, constraint := range c.constraints {
	err := validate(constraint, scope)
	if err != nil {
		return violations.AppendFromError(err)
	}
}
```

2021-05-04 14:29 UTC, strider2038 commented on functions.go
> +			if err != nil {
Если тут вернется violation, то поток управления прервется вместо накопления списка ошибок. Протестируй этот кейс. Мне кажется, что тут лучше придерживаться такой же логики как и с обычным констрейнтом, т.е. возвращать массив ошибок и обрабатывать его через AppendFromError.

2021-05-12 19:59 UTC, nqlad commented on functions.go
> +			if err != nil {
не думаю что такой кейс возможен, тк в функцию передается ViolationList и соответственно обработка через AppendFromError происходит внутри. Ошибка, которая может вернуться это ошибка библиотеки, разве нет?

2021-05-12 20:15 UTC, nqlad commented on functions.go
> +			if err != nil {
а нет, верю

2021-05-13 18:26 UTC, nqlad commented on functions.go
> +			if err != nil {
перепроверил, дефекта нет

2021-05-16 18:51 UTC, strider2038 commented on contraint.go
> +// Sequentially function using to set of constraints that should be validated step-by-step.
**used** to set

2021-05-16 18:54 UTC, strider2038 approved these changes

2021-05-16 18:54 UTC, merged